### ISSUE TITLE
Swagger Spec pasted into editor shows spurious warnings until saved

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#239] opened 2016-10-27 14:33 UTC
The attached Swagger Spec is fine, and shouldn't show any warnings.  But if you copy the text content and paste it into SwagEdit, all of the $ref values (and possibly some others) show warning markers.  

![image](https://cloud.githubusercontent.com/assets/692813/19771362/ad06e5de-9c30-11e6-944f-7859c891e4fa.png)

Saving the Swagger spec seems to resolve this.

This is not high-priority, but if there's a way to prevent this, it would be helpful.

[RestAPI.zip](https://github.com/RepreZen/SwagEdit/files/556142/RestAPI.zip)

**Comment by ghillairet** [comment] 2016-10-31 13:06
I cannot reproduce this issue with the version in the master. @tfesenko can you try to reproduce?

**Comment by tfesenko** [comment] 2016-10-31 15:02
I am not seeing it either. Tried both from sources (on master) and on RepreZen daily build (1.3.3.5609). Added edits to force-validate the model.

I think it was fixed with changed introduced last week.

**Comment by tedepstein** [comment] 2016-10-31 15:28
I am still able to reproduce the error on build 5605, from Friday.  Can you please try on Windows?

**Comment by tfesenko** [comment] 2016-10-31 18:54
I was able to reproduce it on a Mac. 
A key condition here is to **paste** the model text into an existing file which is open in SwaggerEditor. Immediately after pasting the model the editor shows these warnings for refs. After editing it (I added three whitespaces to an arbitrary place) the warnings disappear.

**Comment by tedepstein** [comment] 2016-10-31 20:41
@tfesenko , correct.  I said that in the issue title and description, but next time I'll put it in **bold**.  :-)

**Comment by ghillairet** [comment] 2016-11-07 14:06
Could be related to #206

**Comment by ghillairet** [comment] 2016-11-08 11:03
PR #246 should solve this issue, not sure that solves issues with #206 as it only solves issues with references validation.

**Closed as completed** 2016-11-08 21:23 UTC
Labels: Low Priority
