### ISSUE TITLE
Allow editing of OpenAPI 3.0 code templates in Eclipse Preferences screen 

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#386] opened 2017-09-20 02:01 UTC
We currently have a preferences screen for OpenAPI v2 templates, but we don't seem to have one for OpenAPI v3.

**Comment by tfesenko** [comment] 2017-09-20 11:37
It looks like a duplicate of #348 "OpenAPI V3: Preferences page for code templates"

**Closed as completed by tfesenko** 2017-09-20 11:37 UTC
Labels: OpenAPIv3
