### ISSUE TITLE
KaiZen Editor always warns on valid external reference 

### ISSUE THREAD

**Issue by tedepstein** [RepreZen/KaiZen-OpenAPI-Editor#390] opened 2017-09-21 20:36 UTC
It seems that the editor will always warn on an remote reference, or a certain type of external reference, even when valid.  

"Remote reference" means a reference to a document that is not in the current workspace. This problem was observed specifically on an http reference.  We don't know whether the problem applies to all remote references, or just http, or just https, maybe.

Here's a gist, with a valid OpenAPI 2.0 (Swagger) spec containing schemas:
https://gist.github.com/tedepstein/0e5f5982314f0648377df8782d7b7ccf

Here's an OpenAPI 2.0 spec with a reference to a definition in that gist (using the 'raw' URL for the gist):

```
swagger: "2.0"
info:
  description: Tax Blaster
  version: 1.0.0
  title: TaxBlaster
host: taxblaster.com
basePath: /api
schemes:
- http

paths:

  /taxFilings/{id}:

    get:
      tags:
      - TaxFilingObject
      description: Retrieves a tax filing having the specified id.
      operationId: getTaxFiling
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: ID of the requested TaxFiling
        required: true
        type: string
      responses:
        200:
          description: Successful response, with a representation of the Tax Filing.
          schema:
            # Reference to a Schema Object described in 'definitions' section
            $ref: "https://gist.githubusercontent.com/tedepstein/0e5f5982314f0648377df8782d7b7ccf/raw/96826757aa77ddd6816ff7c3e5ca6903c0f66f2b/schemas.yaml#/definitions/PriceEstimate"
        404:
          description: The requested tax filing was not found.
```

The reference is flagged with a warning:

```
Invalid Reference - SwagEdit was unable to resolve the reference. The value must be a valid JSON Reference (for 
 external references) or JSON Pointer (for local references), and must resolve to an object of the expected type.
```

**Comment by ghillairet** [comment] 2017-09-22 12:50
Duplicate of https://github.com/RepreZen/KaiZen-OpenAPI-Editor/issues/345

**Closed as completed by ghillairet** 2017-09-22 12:50 UTC
Labels: Bug, Duplicate
